### ISSUE TITLE
`in_toto_attestation` broken on Python < 3.9

### ISSUE THREAD

**Issue by woodruffw** [in-toto/attestation#300]
It looks like `in_toto_attestation` is marked for Python 3.7+ but is using annotation features that were only stabilized in 3.9+, e.g. `type[T]` instead of typing.Type[T]`.

From https://github.com/sigstore/sigstore-python/actions/runs/7134485043/job/19429407875?pr=804:

```console
Traceback (most recent call last):
  File "/home/runner/work/sigstore-python/sigstore-python/env/bin/sigstore", line 5, in <module>
    from sigstore._cli import main
  File "/home/runner/work/sigstore-python/sigstore-python/sigstore/_cli.py", line 54, in <module>
    from sigstore.sign import SigningContext
  File "/home/runner/work/sigstore-python/sigstore-python/sigstore/sign.py", line 55, in <module>
    from in_toto_attestation.v1.statement import Statement
  File "/home/runner/work/sigstore-python/sigstore-python/env/lib/python3.8/site-packages/in_toto_attestation/v1/statement.py", line 4, in <module>
    from in_toto_attestation.v1.resource_descriptor import ResourceDescriptor
  File "/home/runner/work/sigstore-python/sigstore-python/env/lib/python3.8/site-packages/in_toto_attestation/v1/resource_descriptor.py", line 8, in <module>
    class ResourceDescriptor:
  File "/home/runner/work/sigstore-python/sigstore-python/env/lib/python3.8/site-packages/in_toto_attestation/v1/resource_descriptor.py", line [22](https://github.com/sigstore/sigstore-python/actions/runs/7134485043/job/19429407875?pr=804#step:5:23), in ResourceDescriptor
    def copy_from_pb(proto: type[rdpb.ResourceDescriptor]) -> 'ResourceDescriptor':
TypeError: 'type' object is not subscriptable
```

**Comment by woodruffw** [comment]
In terms of post-mortems: it looks like this could have been prevented by running tests/lints in CI/CD for the supported Python versions here. If there's interest, I can do that.

**Comment by joshuagl** [comment]
Yes please! If we're going to generate API it would be good to test it comprehensively and have confidence in what we publish.
